blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogIndexView.as_view(), name="index"),
    path('list/', views.BlogListView.as_view(), name="blog_list"),
    path('detail/<int:pk>/', views.BlogDetailView.as_view(), name="blog_detail"),
    path('create/', views.BlogCreateView.as_view(), name="blog_create"),
    path('update/<int:pk>/', views.BlogUpdateView.as_view(), name="blog_update"),
    path('delete/<int:pk>/', views.BlogDeleteView.as_view(), name="blog_delete"),
]

diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
  path('', views.IndexView.as_view(), name="index"),
  path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
  path('diary-list/', views.DiaryListView.as_view(), name="diary_list"),
  path('diary-detail/<int:pk>/', views.DiaryDetailView.as_view(), name="diary_detail"),
  path('diary-create/', views.DiaryCreateView.as_view(), name="diary_create"),
  path('diary-update/<int:pk>/', views.DiaryUpdateView.as_view(), name="diary_update"),
  path('diary-delete/<int:pk>/', views.DiaryDeleteView.as_view(), name="diary_delete"),
]

private_diary/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls')),
    # path('', include('testapp.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

blog/models.py
from accounts.models import CustomUser
from django.db import models


class Blog(models.Model):
    """ブログモデル"""

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    content = models.TextField(verbose_name='本文', blank=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    photo2 = models.ImageField(verbose_name='写真2', blank=True, null=True)
    photo3 = models.ImageField(verbose_name='写真3', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Blog'

    def __str__(self):
        return self.title

blog/forms.py
import os

from django.core.mail import EmailMessage
from django import forms
from .models import Blog

class BlogCreateForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'photo1', 'photo2', 'photo3',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

blog/views.py
from django.contrib import messages
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404
from .models import Blog
from .forms import BlogCreateForm

import logging
logger = logging.getLogger(__name__)



class OnlyYouMixin(UserPassesTestMixin):
    """ ログイン済ユーザのアクセス制御 """

    raise_exception = True

    def test_func(self):
        # URLに埋め込まれた主キーから日記データを1件取得。取得できなかった場合は404エラー
        blog = get_object_or_404(Blog, pk=self.kwargs['pk'])
        # ログインユーザーと日記の作成ユーザーを比較し、異なればraise_exceptionの設定に従う
        return self.request.user == blog.user

class BlogIndexView(generic.TemplateView):
    template_name = "blog_index.html"

class BlogListView(LoginRequiredMixin, generic.ListView):
    """ 日記一覧表示 """

    model = Blog
    template_name = 'blog_list.html'
    paginate_by = 2

    def get_queryset(self):
        blogs = Blog.objects.filter(user=self.request.user).order_by('-created_at')
        return blogs

class BlogDetailView(LoginRequiredMixin, OnlyYouMixin, generic.DetailView):
    """ 記事詳細表示 """

    model = Blog
    template_name = 'blog_detail.html'

class BlogCreateView(LoginRequiredMixin, generic.CreateView):
    """ 記事作成表示 """

    model = Blog
    template_name = 'blog_create.html'
    form_class = BlogCreateForm
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        blog = form.save(commit=False)
        blog.user = self.request.user
        blog.save()
        messages.success(self.request, '日記を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "日記の作成に失敗しました。")
        return super().form_invalid(form)

class BlogUpdateView(generic.TemplateView):
    template_name = "blog_update.html"

class BlogDeleteView(generic.TemplateView):
    template_name = "blog_delete.html"

blog/templates/blog_base.html
{% load static %}

<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon1.ico' %}"/>
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/creative-gh-pages.css' %}" rel="stylesheet"/>

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
    {% block head %}
    <script></script
    {% endblock %}
</head>

<body>
<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom fixed-top">
        <div class="container px-5">
            <a class="navbar-brand" href="{% url 'blog:index' %}">Dark Side</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav me-auto"></ul>
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'diary:index' %}">Private Diary</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% block active_signup %}{% endblock %}" href="{% url 'account_signup' %}">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block active_login %}{% endblock %}" href="{% url 'account_login' %}">Log In</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block header%}{% endblock %}

    {% if messages %}
    <div class="container my-div-style">
        <div class="row">
            <ul class="messages" style="list-style: none;">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}

    {% block contents%}{% endblock %}

    <!-- Footer -->
    <footer class="py-5 bg-secondary">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Dark Side 2021</p>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- SimpleLightbox plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</div>
</body>
</html>

blog/templates/blog_create.html
{% extends 'blog_base.html' %}
{% load static %}

{% block title %}記事作成 | Dark Side{% endblock %}

{% block active_blog_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">作成</button>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Blog Deleteテストページ</title>
  </head>
  <body>
    <h1>Blog Delete World</h1>
  </body>
</html>

blog/templates/blog_detail.html
{% extends 'blog_base.html' %}
{% load static %}

{% block title %}記事詳細 | Dark Side{% endblock %}

{% block active_blog_list %}active{% endblock %}


{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <div class="col-3">
            <strong>タイトル</strong>
        </div>
        <div class="col-9">
            {{ object.title }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>本文</strong>
        </div>
        <div class="col-9">
            {{ object.content|linebreaksbr }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>写真</strong>
        </div>
        <div class="col-3">
            {% if object.photo1 %}
            <img src="{{ object.photo1.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <div class="col-3">
            {% if object.photo2 %}
            <img src="{{ object.photo2.url }}" width="200" height="200"/>
            {% endif %}
        </div>
        <div class="col-3">
            {% if object.photo3 %}
            <img src="{{ object.photo3.url }}" width="200" height="200"/>
            {% endif %}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>作成日時</strong>
        </div>
        <div class="col-9">
            {{ object.created_at }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>更新日時</strong>
        </div>
        <div class="col-9">
            {{ object.updated_at }}
        </div>
    </div>

    <a class="btn btn-success mt-5 mb-3" href="{% url 'blog:blog_update' object.pk %}">編集</a>
    <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'blog:blog_delete' object.pk %}">削除</a>
</div>
{% endblock %}

blog/templates/blog_index.html
{% extends 'blog_base.html' %}
{% load static %}

{% block title %}Web上にキミの黒歴史を公開できるサービス | Dark Siders{% endblock %}

{% block header%}

<!-- Masthead-->
<header class="bg-masthead">
    <div class="container px-4 px-lg-5 h-100">
        <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-8 align-self-end">
                <h1 class="text-white font-weight-bold">キミの黒歴史を見せつけよう</h1>
                <hr class="divider" />
            </div>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}
{% block contents %}
<section class="page-section bg-primary" id="about">
    <section class="container px-4 px-lg-5 fade">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <h2 class="text-white mt-0">Nunc interdum posuere elit sit amet tincidunt!</h2>
        <hr class="divider divider-light" />
        <p class="text-white-75 mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tristique orci et arcu commodo pharetra. Donec consequat dictum ante vitae vehicula. Sed elementum euismod sapien et pellentesque. Aliquam erat volutpat.</p>
        <div class="col-lg-4 text-center mb-1">
            <a class="btn btn-light btn-xl" href="{% url 'blog:blog_list' %}">Show List</a>
        </div>
        <div class="col-lg-4 text-center">
          <a class="btn btn-light btn-xl mb-1" href="{% url 'blog:blog_create' %}">Create New</a>
        </div>
      </div>
    </section>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
  document.body.style.display = 'none';
  jQuery(function($){
    $('body').fadeIn(1000);
    $(window).on("beforeunload",function(e){
        $('body').fadeOut();
    });
  });
  $(function () {
      $(window).scroll(function () {
        $('.fade').each(function () {
          const targetElement = $(this).offset().top;
          const scroll = $(window).scrollTop();
          const windowHeight = $(window).height();
          if (scroll > targetElement - windowHeight) {
            $(this).addClass('view');
          }
        });
      });
    });
</script>
{% endblock %}

blog/templates/blog_list.html
{% extends 'blog_base.html' %}
{% load static %}

{% block title %}記事一覧 | Blog{% endblock %}

{% block head %}{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary float-right" href="{% url 'blog:blog_create' %}">新規作成</a>
            </div>
            {% for blog in blog_list %}
            <div class="post-preview">
                <a href="{% url 'blog:blog_detail' blog.pk %}">
                    <h2 class="post-title">
                        {{ blog.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ blog.content|truncatechars:20 }}
                    </h3>
                </a>
                <p class="post-meta">{{ blog.created_at }}</p>
            </div>
            <hr class="my-4">
            {% empty %}
            <p>記事がありません。</p>
            {% endfor %}

            <!-- ページネーション処理 -->
            {% if is_paginated %}
            <ul class="pagination">
                <!-- 前ページへのリンク -->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                <!-- ページ数表示 -->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
                {% endfor %}

                <!-- 次ページへのリンク -->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog_update.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Blog Updateテストページ</title>
  </head>
  <body>
    <h1>Blog Update World</h1>
  </body>
</html>